apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: worker-pdb
  namespace: asyncflow

  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: asyncflow-platform
    app.kubernetes.io/managed-by: kubectl

spec:

  minAvailable: 1

  selector:
    matchLabels:
      app: worker